name: Docker Build
on:
  workflow_dispatch:

permissions: read-all

jobs:
  action:
    runs-on: slsa
  build:
    permissions:
      id-token: write
      contents: read
      actions: read
      packages: write
    uses: ianlewis/slsa-github-generator/.github/workflows/builder_dockerfile_slsa3.yml@dockerfile-builder
    with:
      tags: "ghcr.io/ianlewis/actions-test:${{ github.ref_name }}-${{ github.sha }}"
    secrets:
      personal_access_token: ${{ secrets.PACKAGES_TOKEN }}
